name: Go
on: [push]
env:
  DOCKER_REG: docker.pkg.github.com
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

#   - name: Get dependencies
#     run: |
#       go get -v -t -d ./...
#       if [ -f Gopkg.toml ]; then
#           curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#           dep ensure
#       fi

#   - name: Build
#     run: go build -v .

#   - uses: azure/docker-login@v1
#     with:
#         login-server: $DOCKER_REG
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image and Push
      run: |
        REPO=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`
        REF=`echo ${{github.ref}} | awk -F/ '{print $NF}'` | tr -cd '[:alnum:]._-'

        CONTAINER_IMAGE=$DOCKER_REG/$REPO/img:${{ github.sha }}
        CONTAINER_IMAGE_ALIAS=$DOCKER_REG/$REPO/img:$REF

        echo '${{ secrets.GITHUB_TOKEN }}' | docker login --username=${{ github.actor }} $DOCKER_REG --password-stdin

        docker build . -t $CONTAINER_IMAGE
        docker push $CONTAINER_IMAGE
        docker tag $CONTAINER_IMAGE $CONTAINER_IMAGE_ALIAS
        docker push $CONTAINER_IMAGE_ALIAS
